[package]
authors = ["Kévin COMBRIAT <kevin@sc0ville.com>"]
edition = "2018"
name = "tailwind-generator"
version = "0.1.0"

[dependencies]
anyhow = "1.0.41"
askama = "0.10.5"
clap = "3.0.0-beta.2"
convert_case = "0.4.0"
cssparser = "0.28.1"
env_logger = "0.8.4"
log = "0.4.14"
