[package]
authors = ["Kévin COMBRIAT <kevin@sc0ville.com>"]
edition = "2018"
name = "style-generator"
version = "0.1.0"

[dependencies]
anyhow = "1.0.42"
clap = "3.0.0-beta.2"
env_logger = "0.9.0"
log = "0.4.14"
style-generator-core = {path = "../style-generator-core"}
url = "2.2.2"
