[package]
authors = ["Kévin COMBRIAT <kevin@sc0ville.com>"]
edition = "2018"
name = "pyaco-generate"
version = "0.1.0"

[dependencies]
anyhow = "1.0.42"
clap = "3.0.0-beta.2"
log = "0.4.14"
notify = "5.0.0-pre.11"
pyaco-core = {path = "../pyaco-core"}
